---
title: "USA Carbon Dioxide (CO2) Emissions from Electricity Generation from 1973 to 2017"
author: "Ely X. Colon"
date: "February 1, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE,
                      warning = FALSE)
```

## Instructions

Create a web page presentation using R Markdown that features a plot created with Plotly. Host your webpage on either GitHub Pages, RPubs, or NeoCities. Your webpage must contain the date that you created the document, and it must contain a plot created with Plotly.

## USA CO2 Emissions from Electricity Generation from 1973 to 2017

```{r CO2, echo = FALSE}
library(plotly)
library(data.table)
library(tidyr)
library(lubridate)
CO2 <- fread("CO2_emissions_data.csv", header = TRUE, sep = ",")
CO2 <- CO2 %>%
        select(YYYY, Value) %>%
        as.data.frame()
# Plot data
plot_ly(data = CO2, x = ~YYYY, y = ~Value) %>%
        
        layout(
                xaxis = list(title = "Date"),
                yaxis = list(title = "Million Metric Ton of CO2")
        )

```